/// @description Initializing vars
playerAng = 0;
turnAng = 0;
maxTurnAng = 6;
is3d = true;
image_speed = 0;
global.control_scheme = "keyboard";
vel = 0;
maxvel = 12;
accel = 0.175;
fric = 0.1;
invertX = -1;
frontAxle = 37;
distancetoWheel = 12;
wheelAngle = 0;
leftWheelX = 0;
leftWheelY = 0;
rightWheelX = 0;
rightWheelY = 0;
global.pfuel = 10000;
trail_init();